name: Active Intel
favicon: null
layout_spectrum: 0.4158328305929899
typography_spectrum: 0.4851675811223686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.42657255730591714
  lightness: 0.00032312539406120777
  saturation: 0.8948030616156757
  rhythmicContrast: 0.07549112406559289
purpose: []
